name: Eval script

on:
  pull_request_target:
    branches: [ master ]

jobs:
  eval:
    runs-on: [self-hosted, linux]

    steps:
    - name: Download results.zip
      run: wget https://github.com/$GITHUB_ACTOR/GLUECoS/raw/$GITHUB_HEAD_REF/results.zip -O results.zip 
    - name: Copy eval scripts
      run: cp -r /root/code/ eval/
    - name: Run Eval
      run: cd eval && ./eval.sh ../results.zip
